### ISSUE TITLE
Nav height

### ISSUE THREAD

**Issue by mahcloud** [RocketNanny/RocketNanny#31]
![image](https://cloud.githubusercontent.com/assets/1529103/14712095/1aeccbe0-0799-11e6-85b4-e72491a81b45.png)

The logo appears a little too low.
The links are a little too high.

I would fix this with:

``` css
li {
  line-height: 55px;
}
li a {
  padding: 0px 16px;
}
.fa {
  line-height: 55px;
}
```

Padding can be tricky between text and non-text items.
Line height will tell text or images that that one line should be this high. Text will auto vertical align.
